inherit_from: configs/rgbd/rgbd_config.yml
Dataset:
  Calibration:
    cx: 960.0
    cy: 1920.0
    depth_scale: 1.0
    height: 1920
    width: 3840
  dataset_path: ./data/indoor_room_synthetic/renders_room_exploration_2_Ex2/PanoramaCam/
  inv_depth: false
  image_downsample: 2