inherit_from: configs/rgb/rgb_config.yml
Dataset:
  camera: "X4 Stick"
  Calibration:
    cx: 960.0
    cy: 1920.0
    depth_scale: 1.0
    height: 1920
    width: 3840
  dataset_path: ./data/indoor_real_world/insta360x4_X4/extension_mount_Ext/02_backforth_turn_Rt/
  inv_depth: false
  image_downsample: 2